# this script splits a single placement.png file generated by LogoIntern into 10 for use
# (modify filename, number, h as required)

filename = "placements.png"
n = 10
h = 1290
dh = h / n

n.times do |slice|
  system "magick #{filename} -crop x#{dh}+0+#{dh * slice} + repage placements#{slice}.png"
end
